In [2]:
import numpy as np

In [12]:
array = np.array([1,2,3,4,5])
print("Numpy array created" ,array )
print("One Dimensions: ", array.ndim)

Numpy array created [1 2 3 4 5]
One Dimensions:  1


In [14]:
array = np.array(1)
print("Zero Dimensions: ", array.ndim)

Zero Dimensions:  0


In [16]:
array = np.array([[1,2,3,4],
                  [5,6,7,8]])
print("Two Dimensions: ", array.ndim)

Two Dimensions:  2


In [ ]:
array = np.array([[[1,2,3,4],[5,6,7,8]],
                  [[9,10,11,12],[13,14,15,16]]])
print(array)
print("Three Dimensions: ", array.ndim)
print("Shape of array: ", array.shape) #[2,2,4] --> 2 blocks, each with 2 rows and 4 columns
print(array[0,0,0]) #accessing first element of first row of first block
print(array[1,1,3]) #accessing fourth element of second row of second block

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
Three Dimensions:  3
Shape of array:  (2, 2, 4)
1
