In [1]:
import numpy as np

In [12]:
array = np.array([1,2,3,4,5])
print("Numpy array created" ,array )
print("One Dimensions: ", array.ndim)

Numpy array created [1 2 3 4 5]
One Dimensions:  1


In [14]:
array = np.array(1)
print("Zero Dimensions: ", array.ndim)

Zero Dimensions:  0


In [16]:
array = np.array([[1,2,3,4],
                  [5,6,7,8]])
print("Two Dimensions: ", array.ndim)

Two Dimensions:  2


In [22]:
array = np.array([[[1,2,3,4],[5,6,7,8]],
                  [[9,10,11,12],[13,14,15,16]]])
print(array)
print("Three Dimensions: ", array.ndim)
print("Shape of array: ", array.shape) #[2,2,4] --> 2 blocks, each with 2 rows and 4 columns
print(array[0,0,0]) #accessing first element of first row of first block
print(array[1,1,3]) #accessing fourth element of second row of second block

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
Three Dimensions:  3
Shape of array:  (2, 2, 4)
1
16


In [7]:
#Scalar Arithmetic
array = np.array([1,2,3])
print(array + 1)
print(array - 1)
print(array * 3)
print(array / 2)
print(array % 2)
print(array ** 2)

[2 3 4]
[0 1 2]
[3 6 9]
[0.5 1.  1.5]
[1 0 1]
[1 4 9]


In [9]:
#Vectorized math functions
array = np.array([1,2,3])
print(np.sqrt(array))

[1.         1.41421356 1.73205081]


*** Numpy round() function
Rounds the values in a NumPy array to the nearest integer

**** Important **** 
NumPy uses "round half to even" (also called banker’s rounding).
That means numbers ending in .5 are rounded to the nearest even number, not always up.

In [ ]:
array1 = np.array([1.2,2.5,3.99]) #number ending in .5 are rounded to the nearest even number
print(np.round(array1)) # rounds the values in a NumPy array to the nearest integer
print(np.pi) #pi value from numpy

[1. 2. 4.]
3.141592653589793


In [16]:
#Exersize- Area of circles
radii = np.array([1,2,3])
print("Area of circle" , np.pi * (radii ** 2))

Area of circle [ 3.14159265 12.56637061 28.27433388]


#Element-wise arithmetic
Operations are applied to each element of an array individually, not to the whole array as one number.

In [21]:
#Element-wise arithmetic
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [25]:
#Comparison operators
scores = np.array([91,85,75,100,82,64])

print(scores > 90) #returns a boolean array indicating which scores are greater than 90
print(scores == 100)
print(scores < 80)
print(scores <= 60)
print(scores[scores > 90]) #returns the scores that are greater than 90

[ True False False  True False False]
[False False False  True False False]
[False False  True False False  True]
[False False False False False False]
[ 91 100]
