In [2]:
import numpy as np

In [12]:
array = np.array([1,2,3,4,5])
print("Numpy array created" ,array )
print("One Dimensions: ", array.ndim)

Numpy array created [1 2 3 4 5]
One Dimensions:  1


In [14]:
array = np.array(1)
print("Zero Dimensions: ", array.ndim)

Zero Dimensions:  0


In [16]:
array = np.array([[1,2,3,4],
                  [5,6,7,8]])
print("Two Dimensions: ", array.ndim)

Two Dimensions:  2


In [ ]:
array = np.array([[[1,2,3,4],[5,6,7,8]],
                  [[9,10,11,12],[13,14,15,16]]])
print(array)
print("Three Dimensions: ", array.ndim)
print("Shape of array: ", array.shape) #[2,2,4] --> 2 blocks, each with 2 rows and 4 columns
print(array[0,0,0]) #accessing first element of first row of first block
print(array[1,1,3]) #accessing fourth element of second row of second block

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
Three Dimensions:  3
Shape of array:  (2, 2, 4)
1


In [16]:
#Slicing using numpy
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

#array[start:end:step]
print(array[1:4:2]) #output: start with index 1 goes upto 4th row step:2 skips the 3rd row


[[ 5  6  7  8]
 [13 14 15 16]]


In [15]:
print("array in reverse order:")
print(array[::-1]) #Gives array in reverse order

array in reverse order:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [17]:
print("all rows and columns with step 2:")
print(array[:,::2]) #Gives all rows and columns with step 2

all rows and columns with step 2:
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [18]:
print("sub array from 1st to 3rd row and 1st to 3rd column:")
print(array[0:3,0:3]) #Gives sub array from 1st to 3rd row and 1st to 3rd column

sub array from 1st to 3rd row and 1st to 3rd column:
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [ ]:
print(array[:, -1]) #last row

[ 4  8 12 16]


In [24]:
print(array[:,:3]) #1st 3 rows

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [ ]:
print(array[:,2]) #3rd column of an array

[ 3  7 11 15]
